version: "3.1"
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nodejs
      - fastapi 

  nodejs:
    image: node:alpine
    environment:
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    ports:
      - "8001:3000"
    volumes:
      - ./node-app:/home/app
    depends_on:
      - php
    command: ["npm", "run", "start:dev"]

  php:
    image: webdevops/php-apache-dev:8.2
    volumes:
      - ./php-app:/app
    ports:
      - "8002:80"
    environment:
      WEB_DOCUMENT_ROOT: /app/public

  fastapi:
    build:
      context: ./fastapi-app  
    volumes:
      - ./fastapi-app:/app
    ports:
      - "8003:80"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
